---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  bundler-audit:
    enabled: false
ratings:
  paths:
  - "**.rb"
exclude_paths:
- examples/
- spec/
- test/
- gemfiles/
